
model_name: "KGIN"

# Common Hyperparameters
latent_dim: 128
n_layers: 3
use_pretrained_weights: False
pretrained_weights_path: train_logs/checkpoints/...
# KGIN-specific Hyperparameters
reg_decay: 0.00001        # L2 regularization coefficient
sim_decay: 0.0001        # correlation penalty coefficient
n_factors: 4           # number of disentangled factors
node_dropout_rate: 0.5
mess_dropout_rate: 0.1
ind: "cosine"        # correlation type: "distance" or "cosine"


