# Core training setup
lr: 0.01
batch_size: 64
num_workers: 2
max_epochs: 300
weight_decay: 0.0001
reg_loss_weight: 0.01
top_k: [5, 10]  

# Optimizer options: adam, adamw, sgd, rmsprop
optimizer: adamw

# Scheduler options: cosine, step, onecycle, reduce_on_plateau
scheduler:
  name: cosine
  t_max: 50
  eta_min: 0.00001

# Example step scheduler
# scheduler:
#   name: step
#   step_size: 20
#   gamma: 0.5

# Example onecycle scheduler
# scheduler:
#   name: onecycle
#   max_lr: 0.005

# Example reduce_on_plateau scheduler
# scheduler:
#   name: reduce_on_plateau
#   factor: 0.5
#   patience: 5
#   monitor: val_recall@10

# Trainer-specific settings
precision: 16             
gradient_clip_val: 1.0
accumulate_grad_batches: 2
experiment_name: "lightgcn_experiment"
run_name: "cart_wishlist_pdp"
log_every_n_steps: 10
check_val_every_n_epoch: 5


neg_per_pos: 1
add_self_loop: False
monitor_metric: "val_recall_at_10"
save_top_k: 1
save_weights_only: True
reload_dataloaders_every_n_epochs: 1
log_computational_graph: True
